Repository Tacaa/UKS-2024, pull requests merged in 2025-08, with the labels that each got.

#167 feat: add register admin functionality front+back
  backend/uks-backend/src/main/java/com/example/uks/controllers/AuthenticationController.java
  frontend/uks-ui/src/app/admin-board/create-administrator/create-administrator.component.css
  frontend/uks-ui/src/app/admin-board/create-administrator/create-administrator.component.html
  frontend/uks-ui/src/app/admin-board/create-administrator/create-administrator.component.ts
  frontend/uks-ui/src/app/organisation-pages/orgs-page/orgs-page.component.html
  frontend/uks-ui/src/app/services/auth/auth.service.ts
Labels: enhancement

#169 Feature 168 superadmin first login app logic
  frontend/uks-ui/src/app/admin-board/super-admin-login/super-admin-login.component.ts
  frontend/uks-ui/src/app/app-routing.module.ts
  frontend/uks-ui/src/app/services/auth/auth.service.ts
  frontend/uks-ui/src/app/shared-modules/wrapper/wrapper.component.ts
  frontend/uks-ui/src/app/user/account-settings/account-settings.component.ts
Labels: enhancement

#175 feat: add super admin's login
  backend/uks-backend/src/main/java/com/example/uks/config/WebSecurityConfig.java
  backend/uks-backend/src/main/java/com/example/uks/controllers/AuthenticationController.java
  frontend/uks-ui/src/app/services/auth/auth.service.ts
Labels: enhancement

#171 Fix/170-Refactor super admin creation and password file logic
  backend/uks-backend/src/main/java/com/example/uks/appstartup/ApplicationStartup.java
  backend/uks-backend/src/main/java/com/example/uks/appstartup/CreateFileOnDesktop.java
  backend/uks-backend/src/main/resources/data.sql
Labels: fix

#173 Fix/172-Add validation and error handling to LogQueryParser
  backend/uks-backend/src/main/java/com/example/uks/analytics/LogQueryParser.java
Labels: fix

#178 Feature 176 search frontend
  frontend/uks-ui/src/app/app-routing.module.ts
  frontend/uks-ui/src/app/app.module.ts
  frontend/uks-ui/src/app/searchpage/searchpage.component.css
  frontend/uks-ui/src/app/searchpage/searchpage.component.html
  frontend/uks-ui/src/app/searchpage/searchpage.component.spec.ts
  frontend/uks-ui/src/app/searchpage/searchpage.component.ts
  frontend/uks-ui/src/app/services/repository/repository.service.ts
  frontend/uks-ui/src/app/shared-modules/wrapper/wrapper.component.html
  frontend/uks-ui/src/app/shared-modules/wrapper/wrapper.component.ts
  frontend/uks-ui/src/app/usage-page/usage-page.component.html
Labels: enhancement

#179 Fix 177 check old password
  README.md
  backend/uks-backend/src/main/java/com/example/uks/appstartup/CreateFileOnDesktop.java
  backend/uks-backend/src/main/java/com/example/uks/controllers/AuthenticationController.java
  backend/uks-backend/src/main/java/com/example/uks/dto/auth/SuperAdminLoginRequest.java
  frontend/uks-ui/src/app/admin-board/super-admin-login/super-admin-login.component.ts
  frontend/uks-ui/src/app/services/auth/auth.service.ts
Labels: bug, enhancement
