Repository Tacaa/UKS-2024, pull requests merged in 2025-07, with the labels that each got.

#55 feat member overview done
  backend/uks-backend/src/main/java/com/example/uks/controllers/OrganisationController.java
  backend/uks-backend/src/main/java/com/example/uks/dto/user/MemberDTO.java
  backend/uks-backend/src/main/java/com/example/uks/exceptions/AccessDeniedException.java
  backend/uks-backend/src/main/java/com/example/uks/services/OrganisationService.java
Labels: enhancement

#56 Feature 41 adding new member
  backend/uks-backend/src/main/java/com/example/uks/controllers/OrganisationController.java
  backend/uks-backend/src/main/java/com/example/uks/dto/organisation/AddMemberDTO.java
  backend/uks-backend/src/main/java/com/example/uks/exceptions/AccessDeniedException.java
  backend/uks-backend/src/main/java/com/example/uks/services/OrganisationService.java
Labels: enhancement

#76 feat: add official repo creation page plus service
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.css
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.html
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.spec.ts
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.ts
  frontend/uks-ui/src/app/app-routing.module.ts
  frontend/uks-ui/src/app/app.module.ts
  frontend/uks-ui/src/app/cardbar/cardbar.component.ts
  frontend/uks-ui/src/app/create-repository/create-repository.component.ts
  frontend/uks-ui/src/app/explore/explore.component.ts
  frontend/uks-ui/src/app/menu-pages/repositories/repositories.component.ts
  frontend/uks-ui/src/app/personal-repository-page-general/personal-repository-page-general.component.ts
  frontend/uks-ui/src/app/services/mock-repository/repository.service.spec.ts
  frontend/uks-ui/src/app/services/mock-repository/repository.service.ts
  frontend/uks-ui/src/app/services/repository.service.spec.ts
  frontend/uks-ui/src/app/services/repository.service.ts
  frontend/uks-ui/src/app/services/repository/repository.service.ts
  frontend/uks-ui/src/app/shared/models/create-official-repository-model.ts
  frontend/uks-ui/src/app/usage-page/usage-page.component.ts
  frontend/uks-ui/src/app/user/user-profile/user-profile.component.ts
Labels: enhancement

#98 fix: update is saved in database
  backend/uks-backend/src/main/java/com/example/uks/services/OrganisationService.java
Labels: bug

#94 feat: simulate push command, by creating tag object
  backend/uks-backend/src/main/java/com/example/uks/controllers/TagController.java
  backend/uks-backend/src/main/java/com/example/uks/dto/tag/CreateTagDTO.java
  backend/uks-backend/src/main/java/com/example/uks/dto/tag/TagDTO.java
  backend/uks-backend/src/main/java/com/example/uks/model/Tag.java
  backend/uks-backend/src/main/java/com/example/uks/repositories/TagRepository.java
  backend/uks-backend/src/main/java/com/example/uks/services/TagService.java
  backend/uks-backend/src/main/resources/data.sql
Labels: enhancement

#86 Test-85-Add unit tests for OrganisationService
  backend/uks-backend/src/test/java/com/example/uks/services/OrganisationServiceTest.java
Labels: unit test

#99 Feature 89 organisation connection
  backend/uks-backend/src/test/java/com/example/uks/services/OrganisationServiceTest.java
  frontend/uks-ui/src/app/app-routing.module.ts
  frontend/uks-ui/src/app/app.module.ts
  frontend/uks-ui/src/app/dialogs/add-members/add-members.component.html
  frontend/uks-ui/src/app/dialogs/add-members/add-members.component.ts
  frontend/uks-ui/src/app/menu-pages/repositories/repositories.component.ts
  frontend/uks-ui/src/app/organisation-pages/organization-members/organization-members.component.css
  frontend/uks-ui/src/app/organisation-pages/organization-members/organization-members.component.html
  frontend/uks-ui/src/app/organisation-pages/organization-members/organization-members.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/organization-members/organization-members.component.ts
  frontend/uks-ui/src/app/organisation-pages/organization-repositories/organization-repositories.component.css
  frontend/uks-ui/src/app/organisation-pages/organization-repositories/organization-repositories.component.html
  frontend/uks-ui/src/app/organisation-pages/organization-repositories/organization-repositories.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/organization-repositories/organization-repositories.component.ts
  frontend/uks-ui/src/app/organisation-pages/organization-settings/organization-settings.component.css
  frontend/uks-ui/src/app/organisation-pages/organization-settings/organization-settings.component.html
  frontend/uks-ui/src/app/organisation-pages/organization-settings/organization-settings.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/organization-settings/organization-settings.component.ts
  frontend/uks-ui/src/app/organisation-pages/organization-teams/organization-teams.component.css
  frontend/uks-ui/src/app/organisation-pages/organization-teams/organization-teams.component.html
  frontend/uks-ui/src/app/organisation-pages/organization-teams/organization-teams.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/organization-teams/organization-teams.component.ts
  frontend/uks-ui/src/app/organisation-pages/organization/organization.component.css
  frontend/uks-ui/src/app/organisation-pages/organization/organization.component.html
  frontend/uks-ui/src/app/organisation-pages/organization/organization.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/organization/organization.component.ts
  frontend/uks-ui/src/app/organisation-pages/orgs-page-create-org/orgs-page-create-org.component.css
  frontend/uks-ui/src/app/organisation-pages/orgs-page-create-org/orgs-page-create-org.component.html
  frontend/uks-ui/src/app/organisation-pages/orgs-page-create-org/orgs-page-create-org.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/orgs-page-create-org/orgs-page-create-org.component.ts
  frontend/uks-ui/src/app/organisation-pages/orgs-page/orgs-page.component.css
  frontend/uks-ui/src/app/organisation-pages/orgs-page/orgs-page.component.html
  frontend/uks-ui/src/app/organisation-pages/orgs-page/orgs-page.component.spec.ts
  frontend/uks-ui/src/app/organisation-pages/orgs-page/orgs-page.component.ts
  frontend/uks-ui/src/app/organization-members/organization-members.component.html
  frontend/uks-ui/src/app/organization-members/organization-members.component.ts
  frontend/uks-ui/src/app/organization-settings/organization-settings.component.html
  frontend/uks-ui/src/app/organization-settings/organization-settings.component.ts
  frontend/uks-ui/src/app/organization-teams/organization-teams.component.html
  frontend/uks-ui/src/app/organization-teams/organization-teams.component.ts
  frontend/uks-ui/src/app/organization/organization.component.ts
  frontend/uks-ui/src/app/orgs-page-create-org/orgs-page-create-org.component.html
  frontend/uks-ui/src/app/orgs-page-create-org/orgs-page-create-org.component.ts
  frontend/uks-ui/src/app/orgs-page/orgs-page.component.html
  frontend/uks-ui/src/app/orgs-page/orgs-page.component.ts
  frontend/uks-ui/src/app/personal-repository-page-general/personal-repository-page-general.component.ts
  frontend/uks-ui/src/app/services/organisation/organisation.service.spec.ts
  frontend/uks-ui/src/app/services/organisation/organisation.service.ts
  frontend/uks-ui/src/app/services/team/team.service.spec.ts
  frontend/uks-ui/src/app/services/team/team.service.ts
  frontend/uks-ui/src/app/shared/dto/organisation/organisation-create.dto.ts
  frontend/uks-ui/src/app/shared/dto/organisation/organisation-update.dto.ts
  frontend/uks-ui/src/app/shared/dto/organisation/organisation.dto.ts
  frontend/uks-ui/src/app/shared/dto/team/team-member.dto.ts
  frontend/uks-ui/src/app/shared/dto/team/team.dto.ts
Labels: enhancement

#101 Feature 100 organisation team pages
  backend/uks-backend/src/main/java/com/example/uks/dto/team/CreateTeamDTO.java
  backend/uks-backend/src/main/java/com/example/uks/dto/team/TeamDTO.java
  backend/uks-backend/src/main/java/com/example/uks/enumeration/TeamPermission.java
  backend/uks-backend/src/main/java/com/example/uks/model/Team.java
  backend/uks-backend/src/main/java/com/example/uks/services/OrganisationService.java
  backend/uks-backend/src/main/java/com/example/uks/services/TeamService.java
  backend/uks-backend/src/test/java/com/example/uks/controllers/TeamControllerTest.java
  frontend/uks-ui/src/app/app.module.ts
  frontend/uks-ui/src/app/dialogs/add-members-to-team/add-members-to-team.component.css
  frontend/uks-ui/src/app/dialogs/add-members-to-team/add-members-to-team.component.html
  frontend/uks-ui/src/app/dialogs/add-members-to-team/add-members-to-team.component.spec.ts
  frontend/uks-ui/src/app/dialogs/add-members-to-team/add-members-to-team.component.ts
  frontend/uks-ui/src/app/dialogs/add-members/add-members.component.html
  frontend/uks-ui/src/app/dialogs/create-team/create-team.component.html
  frontend/uks-ui/src/app/dialogs/create-team/create-team.component.ts
  frontend/uks-ui/src/app/dialogs/edit-team/edit-team.component.css
  frontend/uks-ui/src/app/dialogs/edit-team/edit-team.component.html
  frontend/uks-ui/src/app/dialogs/edit-team/edit-team.component.spec.ts
  frontend/uks-ui/src/app/dialogs/edit-team/edit-team.component.ts
  frontend/uks-ui/src/app/organisation-pages/organization-teams/organization-teams.component.html
  frontend/uks-ui/src/app/organisation-pages/organization-teams/organization-teams.component.ts
  frontend/uks-ui/src/app/organisation-pages/orgs-page/orgs-page.component.html
  frontend/uks-ui/src/app/services/team/team.service.ts
  frontend/uks-ui/src/app/shared/dto/team/add-member.dto.ts
  frontend/uks-ui/src/app/shared/dto/team/create-team.dto.ts
  frontend/uks-ui/src/app/shared/dto/team/team.dto.ts
  frontend/uks-ui/src/app/shared/dto/team/update-team.dto.ts
  frontend/uks-ui/src/app/shared/enum/TeamPermission.ts
Labels: enhancement

#103 feat: overview repositories of a organisation
  backend/uks-backend/src/main/java/com/example/uks/controllers/RepositoryController.java
  backend/uks-backend/src/main/java/com/example/uks/dto/repository/OrganisationRepositoryDTO.java
  backend/uks-backend/src/main/java/com/example/uks/repositories/RepositoryRepository.java
  backend/uks-backend/src/main/java/com/example/uks/services/RepositoryService.java
Labels: enhancement

#108 Feature 107 repositories list for organisations
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.html
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.ts
  frontend/uks-ui/src/app/app-routing.module.ts
  frontend/uks-ui/src/app/app.module.ts
  frontend/uks-ui/src/app/organisation-pages/organization-repositories/organization-repositories.component.html
  frontend/uks-ui/src/app/organisation-pages/organization-repositories/organization-repositories.component.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-collaborators/personal-repository-page-collaborators.component.css
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-collaborators/personal-repository-page-collaborators.component.html
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-collaborators/personal-repository-page-collaborators.component.spec.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-collaborators/personal-repository-page-collaborators.component.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-general/personal-repository-page-general.component.css
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-general/personal-repository-page-general.component.html
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-general/personal-repository-page-general.component.spec.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-general/personal-repository-page-general.component.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-settings/personal-repository-page-settings.component.css
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-settings/personal-repository-page-settings.component.html
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-settings/personal-repository-page-settings.component.spec.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-settings/personal-repository-page-settings.component.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-tags/personal-repository-page-tags.component.css
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-tags/personal-repository-page-tags.component.html
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-tags/personal-repository-page-tags.component.spec.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page-tags/personal-repository-page-tags.component.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page/personal-repository-page.component.css
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page/personal-repository-page.component.html
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page/personal-repository-page.component.spec.ts
  frontend/uks-ui/src/app/personal-repository-pages/personal-repository-page/personal-repository-page.component.ts
  frontend/uks-ui/src/app/personal-repository-pages/repositories/repositories.component.css
  frontend/uks-ui/src/app/personal-repository-pages/repositories/repositories.component.html
  frontend/uks-ui/src/app/personal-repository-pages/repositories/repositories.component.ts
  frontend/uks-ui/src/app/services/repository/repository.service.ts
  frontend/uks-ui/src/app/shared/dto/repository/organisation-repository.dto.ts
Labels: enhancement

#113 Feature 109 connect create repo
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.html
  frontend/uks-ui/src/app/admin-board/create-official-repo/create-official-repo.component.ts
  frontend/uks-ui/src/app/cardbar/cardbar.component.css
  frontend/uks-ui/src/app/create-repository/create-repository.component.css
  frontend/uks-ui/src/app/create-repository/create-repository.component.html
  frontend/uks-ui/src/app/create-repository/create-repository.component.ts
  frontend/uks-ui/src/app/services/repository/repository.service.ts
  frontend/uks-ui/src/app/shared/dto/repository/create-repository.dto.ts
Labels: enhancement

#111 feature/106-Add super-admin auto-creation on startup
  backend/uks-backend/pom.xml
  backend/uks-backend/src/main/java/com/example/uks/appstartup/ApplicationStartup.java
  backend/uks-backend/src/main/java/com/example/uks/appstartup/CreateFileOnDesktop.java
  backend/uks-backend/src/main/java/com/example/uks/repositories/UserRepository.java
  backend/uks-backend/src/main/resources/data.sql
Labels: enhancement

#119 Test/118-Add integration test and reorganize test packages
  backend/uks-backend/src/main/resources/application-test.properties
  backend/uks-backend/src/test/java/com/example/uks/integration/OrganisationControllerIT.java
  backend/uks-backend/src/test/java/com/example/uks/unit/controllers/OrganisationControllerTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/controllers/RepositoryControllerTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/controllers/TeamControllerTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/controllers/UserControllerTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/services/OrganisationServiceTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/services/RepositoryServiceTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/services/TeamServiceTest.java
  backend/uks-backend/src/test/java/com/example/uks/unit/services/UserServiceTest.java
Labels: integration test

#126 Feature 121 delete tags
  backend/uks-backend/src/main/java/com/example/uks/controllers/TagController.java
  backend/uks-backend/src/main/java/com/example/uks/exceptions/TagNotFoundException.java
  backend/uks-backend/src/main/java/com/example/uks/model/Tag.java
  backend/uks-backend/src/main/java/com/example/uks/repositories/TagRepository.java
  backend/uks-backend/src/main/java/com/example/uks/services/TagService.java
  backend/uks-backend/src/main/resources/data.sql
Labels: enhancement

#134 test/133-Add integration tests for RepositoryController
  backend/uks-backend/src/test/java/com/example/uks/integration/RepositoryControllerIT.java
Labels: integration test

#145 feat: add superadmin options
  frontend/uks-ui/src/app/admin-board/create-administrator/create-administrator.component.css
  frontend/uks-ui/src/app/admin-board/create-administrator/create-administrator.component.html
  frontend/uks-ui/src/app/admin-board/create-administrator/create-administrator.component.ts
  frontend/uks-ui/src/app/admin-board/super-admin-login/super-admin-login.component.css
  frontend/uks-ui/src/app/admin-board/super-admin-login/super-admin-login.component.html
  frontend/uks-ui/src/app/admin-board/super-admin-login/super-admin-login.component.spec.ts
  frontend/uks-ui/src/app/admin-board/super-admin-login/super-admin-login.component.ts
  frontend/uks-ui/src/app/app-routing.module.ts
  frontend/uks-ui/src/app/app.module.ts
Labels: enhancement

#140 test/136-Adding unit tests for TagService
  backend/uks-backend/src/test/java/com/example/uks/services/TagServiceTest.java
Labels: unit test

#141 test/137-Adding unit tests for TagController
  backend/uks-backend/src/test/java/com/example/uks/unit/controllers/TagControllerTest.java
Labels: unit test

#143 test/142-Adding integration tests to TagController
  backend/uks-backend/src/test/java/com/example/uks/integration/TagControllerIT.java
Labels: integration test

#153 feat: add delete tag
  frontend/uks-ui/src/app/repository-page-tags/repository-page-tags.component.css
  frontend/uks-ui/src/app/repository-page-tags/repository-page-tags.component.html
  frontend/uks-ui/src/app/repository-page-tags/repository-page-tags.component.ts
  frontend/uks-ui/src/app/services/tag/tag.service.ts
Labels: enhancement
